### ISSUE TITLE
Vue devtools still broke application

### ISSUE THREAD

**Issue by xar** [pubkey/rxdb#1126]
## Case
Vue devtools still broke application with rxdb.

## Issue
With rxdb 8.1 with vue dev tools enabled I still get error. This time bit different:

```
TypeError: Cannot read property 'getValue' of undefined
    at Object.get _data [as _data] (rx-document.js?8769:36)
    at Object.get (rx-document.js?8769:182)
    at Object.eval [as id] (rx-document.js?8769:440)
```

```
export var basePrototype = {
  /**
   * because of the prototype-merge,
   * we can not use the native instanceof operator
   */
  get isInstanceOfRxDocument() {
    return true;
  },

  get _data() {
    return this._dataSync$.getValue(); <-
  },
```
I'm really not sure why dataSync$ is undefined.

## Info
  - Browser
  - IndexedDB
  - Typescript, Vue

**Comment by pubkey** [comment]
Vue is a hack by itself :)

**Comment by pubkey** [comment]
@xar does the error occur when you add the document to the vue-state or before that?

**Comment by PeterKnight** [comment]
My Vue related errors went away when I switched to feeding Vue instances raw values from RxDB based queries using JSON.parse() and stringify() instead. That way you don't have two tools trying to make your data reactive. It might even be best practice?

**Comment by pubkey** [comment]
@PeterKnight yes, using plain objects inside of a components state is recommended by me, because it makes it easier to debug problems. A `RxDocument` mutates itself over time, so when you add it and find a bug, you can not be sure what state the document had at this point of time.

Note that you can call `myRxDocument.toJSON()` to get a plain object-representation of  the document. Then you do not have to call JSON.parse() and stringify().

But this is still a bug and adding RxDocuments to the vue-state should work. I will try to fix.

**Comment by pubkey** [comment]
Fixed equal to https://github.com/pubkey/rxdb/blob/master/dist/es/rx-document.js#L182

**Comment by pubkey** [comment]
I added a better fix and tested it with vue devtools.
I still do not know why this bug appears. I think the current implementation of the prototype-merging is overly complicated. We should refactor it in the future and then can better fix it.
