### ISSUE TITLE
first local change then save to database. 

### ISSUE THREAD

**Issue by leozale** [pubkey/rxdb#1269]
## Case
new feature

## Issue
When `rxdocument.name = "me"`, first local change then save to database. because in real-time environments  need speed.

## Code
```js

// first change local object
rxDoc.arr.push({name:"test"});
rxDoc.nodes[0].x = 129;
rxDoc.nodes[1].x = 121;
rxDoc.nodes[2].x = 120;

// then auto save

```

**Comment by leozale** [comment]
Current way
```js
const proxyDoc = Doc.newDocument(this.toJSON());
proxyDoc.arr.push({name:"test"});
proxyDoc.nodes[0].x = 129;
proxyDoc.nodes[0].x = 129;

proxyDoc.nodes[0].x = 129;



```

**Comment by leozale** [comment]
solved by plugin , see :
https://github.com/leozale/rxdb-plugin-proxy

```js
  const doc = await Doc.insert({
    name: "first"
  });
  const pdoc = doc.proxy();
  pdoc.change("leo");
  console.log(pdoc.name, doc.name); // real-time out: "leo first"

  await pdoc.store(); // save doc
  console.log(pdoc.name, doc.name); // out: "leo3 leo3"
```

**Comment by pubkey** [comment]
This behavior was removed in the last major release.
Also see https://github.com/pubkey/rxdb/blob/master/orga/releases/8.0.0.md#setters-are-only-callable-on-temporary-documents
The problem was that we cache/reuse the documents for performance and when multiple components of your application modify the document-state, you have strange bugs that are hard to debug.

But having a seperate proxy that is modified could be a good solution.

**Comment by leozale** [comment]
Ok, if native have **rxdoc.temporay** or **rxdoc.proxy** getter API is nice , beacause :

1. **rxdoc#atomicupdate(oldDoc=>)**  API purpose is to operate data in batches, but **oldDoc** unable to enjoy the **functions** 

2. **RxCollection.newDocument(initalData)** can create a temporay doc , but only once. and programmer knows which methods can be called for RxDocument or temporay's document.

### Code example
```js
const proxy = rxdoc.proxy;  // getter a temporay document , it has old data.
proxy.func1();
proxy.func2();
proxy.save(); //  if proxy is new, then insert it.  else if it is **rxdoc.proxy** , then to update.
```
