### ISSUE TITLE
Provide oldData in changeEvent

### ISSUE THREAD

**Issue by tonyxiao** [pubkey/rxdb#1389]
I noticed that in `RxDocument`, the `_saveData` function takes both `newData` and `oldData`. 

```js
    /**
     * saves the new document-data
     * and handles the events
     * @param {any} newData
     * @param {any} oldData
     * @return {Promise}
     */
    _saveData(newData, oldData) {
```

However, only the `newData` is provided in change event. I'm trying to maintain a running sum from a field of each document, and need both the previous value and the next value to be able to effectively maintain the sum. It seems that the underlying pouchdb `changes` api does not provide old data, is that the reason why rxdb doesn't provide it either? And are there usage patterns where `changeEventfromPouchChange` may never be called and therefore it's possible to get the `oldData` with each change?

**Comment by pubkey** [comment]
This is a problem I have in mind for a long time now.
Pouchdb does not emit the previous state when a document changes.
We cannot assume that all writes are done over the RxDB-layer. For example the replication plugin will do direct writes to pouchdb. RxDB uses the [watch-for-changes-plugin](https://rxdb.info/custom-build.html#watch-for-changes) to emit these changes into the RxDB events-stream. Also other plugins can be used that do things with pouchdb directly.
And because we cannot assume all events contain the old data, I did not add this to RxChangeevent.

There would be a huge benefit when the oldData is emitted on each change. For example the [QueryChangeDetection](https://rxdb.info/query-change-detection.html) can have better optimisations. I have done a prove of concept for that with mongodb which emits the oldData in the events.

CouchDB does also [not emit the oldData](https://docs.couchdb.org/en/2.2.0/api/database/changes.html) which is why this will not be included into pouchdb. There could be a way to monkeypatch this on [pouchdb-core](https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-core) or add this with some kind of hooks.

**Comment by tonyxiao** [comment]
Got it. under the current circumstances, how would you recommend maintaining a real-time aggregate sum of a single field on each document without re-reading the entire database for every update?

**Comment by pubkey** [comment]
Since you cannot rely on increasing/decreasing a single number, you have to keep a Map with key->sum-value for each document. On each event you can compare the current value with the one in the map and update the map and also the sum accordingly.
This will of course only work if you do not use `skip` or `limit` in your query.

**Comment by tonyxiao** [comment]
Gotcha. Basically maintain the old document ourselves (a single field of it merely helps with saving memory I imagine) and more or less omitting our own change feed with oldDoc + newDoc? I wonder if that's a pattern common enough to worth adding into rxdb core?

**Comment by pubkey** [comment]
Yes exactly what I meant.
The count-feature was requested some times and is added to the [backlog](https://github.com/pubkey/rxdb/blob/master/orga/BACKLOG.md#rxquerycount).
However it was never priority for me so I did not implement it.
Also I would be better to fix getting the old-data from an event first, then the count() max() sum() etc. have a better implementation. Also the query-change-detection could then move out of the beta-mode.

**Comment by pubkey** [comment]
Sry, didnt want to close this
