### ISSUE TITLE
Opinion wanted: Which sort-syntax should RxDB support?

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#1972]
So for the next major version I want to clarify which sort-syntax RxDB should support. There are different standards on how sorting works with nosql-(mango)-queries.

1. Option one like [mongoDB](https://docs.mongodb.com/manual/reference/method/cursor.sort/)
```json
{
  "sort": {
    "age" : -1,
    "posts": 1
  }
}
```

2. Option two like [pouchdb-find](https://pouchdb.com/guides/mango-queries.html#query-language)
```json
{
  "sort": [
    "-age",
    "posts"
  ]
}
```

3. Option three like [couchDB](https://docs.couchdb.org/en/2.2.0/api/database/find.html#sort-syntax)
```json
{
  "sort": [
    {"age": "desc"},
    {"posts": "asc" }
  ]
}
```
EDIT: Pouchdb also supports this syntax, even if it is not documented.

4. Option four, [proposed by waynebloss](https://github.com/pubkey/rxdb/issues/1972#issuecomment-608949713)

```json
{
  "sort": {
    "age": "desc",
    "posts": "asc"
  }
}
```

To make it easier to maintain, I want to define exactly one sort-syntax and only allow that one. If you have any opinion about sort-syntaxes, write it here.

~Atm I am tending for option nr 3 because it is possible to define the versions fields with typescripts `keyof`. Also I think that `1` and `-1` are more confusing then `asc` and `desc`.~

EDIT: I am now tending to option nr 4, see comments below.

**Comment by stevenroussey-privicy** [comment]
3

**Comment by ExauceFiction** [comment]
Agreed, nr 3 is much more explicit, which is always better for readability + simplicity for newcomers.
-age is horrible!
And if I see -1 and 1... I will always try 2 or -3, just to see what happens!

**Comment by waynebloss** [comment]
What about

```js
{
  "age": "desc",
  "posts": "asc"
}
```

**Comment by waynebloss** [comment]
One other thought about this - arrays provide the ultimate safety against losing the order of your keys. With that in mind and for the sake of brevity, I wonder if it would be useful to consider option 5:

```js
{
sort: [
    "age: desc",
    "posts: asc"
  ]
}
```

This is similar to option number 2 where you have information embedded in the string. Of course, same as option 2, things get a little messier when you have a field name or sort order as a variable...that makes it a little less _clean_ IMO.

```js
{
  "sort": [
    `age: ${sortAgeOrder}`,
    `${sortOtherField}: ${sortOtherOrder}`
  ]
}
```

Here's how I would rate each of these:

| Opt   	| Example   			| Normal	| Simple	| Extendable	| Intuitive   	|
|---	|---	|---	|---	|--	|--	|
| 1   	| `{sort:{age: -1, posts: 1}}`			| -	| +	| +	| -	|
| 2   	| `{sort:["-age","posts"]}`				| +	| +-	| -	| -	|
| 3   	| `{sort:[{age:"desc"},{posts:"asc"}]}`	| +	| -	| ++	| +	|
| 4   	| `{sort:{age:"desc",posts:"asc"}}`		| -	| +	| +	| +	|
| 5   	| `{sort:["age:desc","posts:asc"]}`		| +	| +-	| -	| +	|

Reasoning:

I deducted a **Normal** point for objects, since it's easy to have a bug where you lose the order of the fields. Array representations gain a point for guaranteeing order.

A structure gains a **Simple** point for being flatter, loses a point for being more nested and loses a point if it embeds information inside a string.

An option is **Extendable** if an alternative value type could be assigned in the future (so for example `age: -1` could be extended later to accept `age:{order:-1, nullOption: xyz }`) without a breaking change. It's more extendable if the existing structure supports that out of the box.

An option is **Intuitive** if it uses a widely recognized and more commonly used pattern rather than a less commonly used pattern. (e.g. words "asc/desc" instead of numbers or prefix operators embedded in strings)

**Comment by ExauceFiction** [comment]
I like very much how you've made this decision table, and I will definitely use it for my own decisions now! Thanks for that :)

Now, I would go with Option 3 because extensibility is an important feature.
I feel also comfortable to use an <Array> of sorting options to sort an <Array> of columns.

My two cents...

**Comment by waynebloss** [comment]
Thanks. Sounds like a good choice.

One small problem I could see with extending Option 3 would be the fact that field names might collide with your extension.

If you trade the compatibility with CouchDB for a slightly more normal form, you could have this Option 6:

```js
{
  "sort": [
    { "by": "age", "order": "desc" },
    { "by": "posts", "order": "asc" }
  ]
}
```

but then again this increases the complexity as is to be expected when normalizing something.

A winning compromise might be to extend Option 3 by reserving a prefix character like `$` for future extensions, so you could do:

```js
{
  "sort": [
    { "age": "desc" },
    { "posts": "asc", "$someNewOption": true }
  ]
}
```

**Comment by pubkey** [comment]
@waynebloss thank you for your amazing contribution to the discussion.
I spend some hours thinking about your option 4. It is simple, can be defined with typescript and is easy to implement, read and check. The only thing is that the sorting is dependent on the order of an objects properties and also it would mean that RxDB defines the next `standard`. I would be ok with that.

I see a problem with option 5 because it cannot be defined it via typescript. Also the string has to be parsed each time the code needs to understand the sorting logic.

Having an extendable syntax is not something we should care about now. When there needs to be additional information attached to the sorting, then the user should use a different property of the query like `sortMeta` or whatever. This came out to be also the best approach with RxDB's additional data inside of jsonschema which is changed in the next major version (also see #1655 ). There in the past we had the `index` field inside of the schema, but it is much easier to define all index fields at the top level with a separate attribute.

**Comment by ExauceFiction** [comment]
@pubkey Agreed. No need to worry about extension name conflicts.

**Comment by pubkey** [comment]
I found out now why pouchdb/couchdb's mango query has that sort syntax (option 3).
It is specified [here](https://github.com/cloudant/mango#sort-syntax) and it looks like they had problems with serializing/deserializing json objects while maintaining the attribute order in the objects.

Quote:
> Note that it is highly recommended that you specify a single key per object in your sort ordering so that the order is not dependent on the combination of JSON libraries between your application and the internals of Mango's indexing engine.

**Comment by trik** [comment]
3

**Comment by pubkey** [comment]
Closing this. Let's use options 3.
I tried to implement option 4 but even RxDB it self has problem with maintaining the attributes order.
