### ISSUE TITLE
React native

### ISSUE THREAD

**Issue by matiit** [pubkey/rxdb#2]
If it's good for working on the react-native - maybe it's worth adding it to the README among ~others~ other frameworks?

**Comment by pubkey** [comment]
Hello @matiit . I have not listed react-native currently because I have not yet tested if it works.
Since react-native uses asyncStorage, you can in theory use RxDB with the [asyncstorage-down](https://github.com/tradle/asyncstorage-down) adapter.

```js
var RxDB = require('rxdb');
RxDB.plugin(require('pouchdb-adapter-leveldb'));
RxDB.plugin(require('asyncstorage-down'));
RxDB.create('mydb', 'asyncstorage-down');
```

I will add an react-native-version to the [examples](https://github.com/pubkey/rxdb/tree/master/examples) in the next days and can then add it to the compatibility-list.

**Comment by ewnd9** [comment]
You can also try `pouchdb-adapter-asyncstorage` https://github.com/stockulus/pouchdb-react-native/tree/master/packages/pouchdb-adapter-asyncstorage

**Comment by pubkey** [comment]
I now got a working example with [react-native](https://github.com/pubkey/rxdb/tree/master/examples/reactNative).
