### ISSUE TITLE
Add option to switch on debug logging

### ISSUE THREAD

**Issue by campbellbartlett** [pubkey/rxdb#2489]
## Case
I've noticed a lot of commented out log statements throughout the source code (I've only really looked at the GraphQL plugin closely so far). Do you think there is a case to add a verbose flag that is an optional parameter that a developer can provide when calling methods like syncGraphQl? When the flag is true, these log statements would be called. The flag would default to false but would make it easier for developers to find problems when debugging.

This could also include log statements to print out things like the documents returned from the graphQl endpoint, the latest document retrieved from the Pouch and the result of runPull and runPush etc.

## Issue
I was having an issue with my setup, and in the end I had to download the rxdb source code and add back these logging statements myself, plus connect a debugger to work out what was wrong. 

## Info
  - Environment: (Node.js)
  - Adapter: (IndexedDB/Localstorage/LevelDB/GraphQl)
  - Stack: (Typescript, React)

**Comment by pubkey** [comment]
I decided against having a debug mode in the past. I know pouchdb has one but I see the tradeoffs differently.
Also I do not want to have a debug mode in one plugin only, it should be on all of RxDB or nothing.

I think it would be better to apply more checks and throw errors if the plugin is used wrong. Can you describe what your problem was? Maybe we can find a way to prevent this exact problem in the future.
