### ISSUE TITLE
CouchDB sync issue on electron (leveldown)

### ISSUE THREAD

**Issue by ravi-poonia** [pubkey/rxdb#2723]
### Case
Continuation of : [#2717 ](https://github.com/pubkey/rxdb/issues/2717) 

### Issue:
During sync, all the documents in remote couchDB are pulled in by all the other collections.

### Environment
Electron, leveldown, nodemon

### Code
 [You can reproduce the issue using this example repo, go through Readme for more details](https://github.com/ravi-poonia/couchbd-sync-testing.git)

**Comment by sebastian-schlecht** [comment]
I am not sure whether this is related, but we started investigating RxDB as a base for our sync mechanism lately and it seems to me that each collection is stored in it's own pouch. Once you start replicating to a **single** couchDB instance, it will cross-populate the other collections. You will need to have replication filters in place to get only the data that you want. 

https://rxdb.info/replication.html

Since couch doesn't have a notion of collections, you'll need to add a field to your documents that identifies its type.

Please take my answer with a big grain of salt. We're just starting with RxDB and this is preliminary intel from our end.

**Comment by ravi-poonia** [comment]
that makes a lot of sense.I was assuming RxDB was managing the conversion of multiple collections into a single pouch for Couch and vive-versa internally, maybe this should be add to the docs so others don't run into the same issue.Thank you for sharing the info

**Comment by pubkey** [comment]
Yes. RxDB assumes each collection has its own remote couchdb instance.
There are multiple reasons for that. On is that couchdb replication is slow and splitting documents is not really possible in a performant way.
Please add stuff to the docs if you find that some information is missing.
