### ISSUE TITLE
GraphQL conflict resolution

### ISSUE THREAD

**Issue by MentalGear** [pubkey/rxdb#2771]
Thank you for this amazing library and your continous excellent work on it. I went over the GraphQL guide, and it mentions that conflict resolution should be done server-side. Does this means using graphQL it won't be possible to notify the user of a conflicht while he's editing data, like in the excellent vue example ?
https://github.com/pubkey/rxdb/tree/master/examples/vue

**Comment by pubkey** [comment]
Yes you are right. The replication assumes that all conflicts are handled on the server and the clients receive the properly resoluted document from the server.
I decided for this because the it makes the whole replication protocol way more simple and faster. You can still implement custom client side conflict resolution on top if this.

**Comment by MentalGear** [comment]
Thanks for the explication & your amazing work, Daniel ! Yet, I think one of the great features why people chose rxdb (and/or couchdb) is that it reduces complexity, especially for difficult tasks like conflict resolution. In that sense, it's a quite a big step back (feature difference) when using this lib with graphQL vs. couchdb, especially since I understand that graphQL is meant to be the future of rxdb.
