### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by ssured** [pubkey/rxdb#30]
What is the targeted browser support? The README shows only Chrome and FF. What about Safari, IE and Edge?

![image](https://cloud.githubusercontent.com/assets/2558804/22122829/b447e1e0-de89-11e6-9528-7f29a11c5ee2.png)

PouchDB has a nice list here: https://pouchdb.com/learn.html#browser_support. Maybe this list can be referenced in the readme?

**Comment by pubkey** [comment]
The automated tests currently only run on firefox and chrome. So when coding, these browsers will get tested automatically and the dev can assure that everything works as expected. Of course before each release I test manually at other browsers.

So since there is no automated testing strategy for the other browsers, I can not add them to a list.

**Comment by ssured** [comment]
Your answer is interesting and I'll see if I can make a PR for the readme. Originally not seeing IE kept me away, but I now understand IE & Safari should be supported too, but are not automatically checked.
Awesome news!

**Comment by pubkey** [comment]
The automated tests now run on all browsers on the system. I can run them on my virutal-machine with IE11, and they work.

Could you make a PR with the icons of IE and edge?
