### ISSUE TITLE
Population function has any type

### ISSUE THREAD

**Issue by special-character** [pubkey/rxdb#3152]
## Case
Small type issue!

## Issue
In the TS types, I see the `populate` function is typed like:
```
populate(objPath: string): Promise<RxDocument<RxDocumentType, OrmMethods> | any | null>;
```

The `any` makes it so the overall return type is `any`. 

ex: 

<img width="583" alt="CleanShot 2021-05-13 at 13 24 15@2x" src="https://user-images.githubusercontent.com/5407471/118183189-acf11080-b3ee-11eb-9354-9ae6b67349ce.png">

If I take out the `any` it has the type I would expect

<img width="594" alt="CleanShot 2021-05-13 at 13 24 36@2x" src="https://user-images.githubusercontent.com/5407471/118183233-b8443c00-b3ee-11eb-9db2-9fe9538f547c.png">

I think this TS change is potentially "breaking" if people use the types incorrectly but it should be pretty simple to fix. Happy to take a look at doing this if it makes sense!

**Comment by pubkey** [comment]
Hi. Thank you for investigating.
In the past, if the API was broken, fixing the bug was not considered a breaking change, even if people used workarounds.
Please make a pull request. Also you might want to ad a test to the [typings tests](https://github.com/pubkey/rxdb/blob/master/test/typings.test.ts)

**Comment by special-character** [comment]
Thanks @pubkey, will do!

**Comment by special-character** [comment]
@pubkey Sorry I forgot to do this. If/when I do open a PR I will link back to this issue.
