### ISSUE TITLE
Enable `noUncheckedIndexedAccess`

### ISSUE THREAD

**Issue by seanwu1105** [pubkey/rxdb#3204]
## Case

Enable  [the `noUncheckedIndexedAccess` compiler option](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) to prevent `undefined` value when accessing properties via index.

## Issue

By enabling this flag, projects depending on this library could also apply the flag without [the `skipLibCheck` option](https://www.typescriptlang.org/tsconfig#skipLibCheck) which degrades type checking.

I could provide a pull request if you think it would be helpful. However, since this wonderful project is relatively complex, it would be hard for me to get it correct. I will still do my best.

Also, to enable the flag, the `jsonschema-key-compression` library with the https://github.com/pubkey/jsonschema-key-compression/pull/173 fix must be released first to pass the compiler check.

**Comment by pubkey** [comment]
Hi. I released a new version of `jsonschema-key-compression`.
Please make a PR with the missing stuff.

**Comment by pubkey** [comment]
@seanwu1105 I have a question:
When you import rxdb, the typings do not come directly from the source code, but from the generated [types directory](https://github.com/pubkey/rxdb/tree/master/dist/types).
So having `noUncheckedIndexedAccess` while using rxdb should not result in any error because it will take the typings files and not touch the source files?

**Comment by seanwu1105** [comment]
@pubkey

Yes, I think enabling `noUncheckedIndexedAccess` will not change any behavior of source files except typing files. Some parts of source files might be changed as I need to add some type assertions in TypeScript sometimes. All compilation errors are generated from TypeScript compiler when it is doing type checking.

Apart from that, the tests for Angular, React and Vue are failed due to time exceeding. I am not sure the cause. Could you help me with that?

**Comment by seanwu1105** [comment]
@pubkey

Yes, you are correct. I was wrong about the rationale when creating this issue. I find that the error when I use RxDB with `noUncheckedIndexedAccess` is caused by the old version of jsonschema-key-compresssion library, whose typing is from TypeScript source directly.

If you think the PR #3215 is unnecessary, please close the PR and this issue, though I think it might be helpful for safer null-checking.

Thanks for your time and clarification on my misunderstanding! :)

**Comment by pubkey** [comment]
Hey no problem. I also see a value in having `noUncheckedIndexedAccess` so we should add this in the future. The problem is see at the moment is that we migrated from normal javascript to typescript, so the code is written in a way that needs many null-check to be typesafe. So I will copy some parts from your pull request when I have the time, but much of the code has to be rewritten instead.

**Comment by seanwu1105** [comment]
Great. Besides, could you release RxDB with the latest jsonschema-key-compression? It would be helpful for any project depending on RxDB to enable the flag.
