### ISSUE TITLE
ANNOUNCEMENT: Beta of 10.0.0 can now be tested

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#3279]
Hi everyone.
The beta version of `10.0.0` can now be tested.
You can install it via `npm install rxdb@10.0.0-beta.8`

Writing about the changes: https://github.com/pubkey/rxdb/blob/release/10.0.0/orga/releases/10.0.0.md
Branch for PRs: https://github.com/pubkey/rxdb/tree/release/10.0.0

Please write in this issue for discussion and problem solution.

**Comment by chrisdrackett** [comment]
I'm very excited about the addition of `RxStorage` and have been thinking about what the upgrade path for that might be. The following is my concern, but I haven't fully looked into it:

1. Users phone downloads new app in the background that includes RxDB 10.0 and new storage background
2. user goes off grid and opens the app
3. at this point all the users data is in the old storage, but the app is setup to use the new storage.

because the user does not have access to the server at this point, I'm curious if there needs to be a migration path that can run on device? In our case that might look like connecting to both `pouchdb-adapter-react-native-sqlite` and a new `sqlite` RxStorage and replicating between them?

I know in theory it's possible to do something like this with `InMemory` replication, but I have no experience with it.

**Comment by phal0r** [comment]
@chrisdrackett 
replication is only supported between pouch db instances. Since RxStorage allows us to implement new other storages, they won't be compatible witch pouchdb - RxStorage is an abstraction layer higher. I think you can create 2 RxDB instances in your app. One with the old storage and one with the new storage configured, then you can implement some custom migration code, which transfers your data from the old to the new database. You need to check, if it's the first time launching the app with the new database and execute this logic, if not just boot the app normally and proceed with the new data in the new database.

Once all your users have updated to the new version, you can remove the migration code in future releases.

**Comment by raveclassic** [comment]
Hey @pubkey!

First, thanks for such an amazing lib and even more thanks for pushing it its v10 major. It's really good to see such project is actively developed and maintained.

Now, I would like to help here and to give back to OSS. I'm not familiar with library's internals but I would like to be so and I think the best approach for me would be to help you with addressing existing TODOs (where possible), aligning the code better with existing tslint/eslint rules, finally improving strictness of TypeScript code (reducing amount of `any` types, type casts and other unsafe constructs).

Before I start, I'd like to ask you if you would accept such PRs that don't change the logic but aim at increasing the correctness and soundness of library's type level? If so I think I could try to open some of them in the next few days. What do you think?

**Comment by DominikGuzei** [comment]
@pubkey is the [current documentation website](https://rxdb.info) already up-to-date with v10? I would like to try RxDB in one of my projects but am unsure if the breaking changes would trip me up on my first steps?

I would be fine if it is kinda up-to-date and I can gather the missing information on the run. Also, like @raveclassic I would be interested in contributing to this project, as I think it's one of the more solid solutions for offline-first, real-time DBs that also work with relational databases.

More specifically I'm interested in an integration with Hasura, like they describe here: https://hasura.io/blog/building-an-offline-first-web-app-with-rxdb-hasura

**Comment by DominikGuzei** [comment]
@raveclassic i found this comment https://github.com/pubkey/rxdb/issues/3168#issuecomment-866777223 where @pubkey describes how we can consume the v10 documentation

**Comment by DominikGuzei** [comment]
And it seems like the current documentation website is already updated to v10 … at least it seems to mirror the v10 branch docs
