### ISSUE TITLE
ES Module support for Node.js without any bundler

### ISSUE THREAD

**Issue by adrian-branescu** [pubkey/rxdb#3422]
## Case
This is a feature request for ES Module support without any bundler.

## Issue
The ES version of the code that you produce is useless without a bundler like rollup.

This is because you have relative imports without file extension, you lack the key `"type": "module"` in `package.json` and you also lack the conditional `exports` key e.g.
```javascript
"exports": {
    "./plugins": {
        "./dev-mode": {
            "require": "./dist/lib/plugins/dev-mode/index.js"
            "import": "./dist/es/plugins/dev-mode/index.js"
        }
    }
}
```
With the above example `require()`, static & dinamic `import` will work. As well as any modern bundler.

## Info
  - RxDB Version: 9.x
  - Environment: Node.js
  - Adapter: -
  - Stack: Vanilla ES

## Code

```javascript
import { RxDBDevModePlugin } from 'rxdb/plugins/dev-mode';

console.log(RxDBDevModePlugin);
  /* ... */
```

**Comment by pubkey** [comment]
Hi @adrian-branescu 
This topic is [in the backlog already](https://github.com/pubkey/rxdb/blob/master/orga/before-next-major.md#use-exports-field-in-packagejson).
I could not implement this right now, because it means we need a breaking change to not break #2798 again.
The root module must have set `sideEffects: true` while the others must have set it to `false`. This is not possible via the exports field, so I wanted to wait with it for the next major release where we could change the root package so we have `sideEffects: false` everywhere.

**Comment by pubkey** [comment]
@adrian-branescu 
Ok so I figured out how to fix the sideEffects flag. https://github.com/pubkey/rxdb/commit/4620379a5ff6db03cf287084c9a5c0c13a28b9e4
So we can now accept a PR to use the exports field in the package.json.

**Comment by pubkey** [comment]
I am closing this because it will be a breaking change.
A PR is still welcomed, otherwise I will do it when I release the next major version.
Added to the list [here](https://github.com/pubkey/rxdb/blob/master/orga/before-next-major.md#use-exports-field-in-packagejson)
