### ISSUE TITLE
Attachments: "digest" and "length" are not generated when using storage that is not based on pouch

### ISSUE THREAD

**Issue by nothingkid** [pubkey/rxdb#3548]
We implemented our own idb storage. We expected "digest" and "length" to be generated when attachment is created, but unfortunately these properties are undefined.

![Screenshot_28](https://user-images.githubusercontent.com/22461210/144758440-31432d76-4360-41fb-b210-873d9d39a1e7.png)
![Screenshot_27](https://user-images.githubusercontent.com/22461210/144758329-b4d9af00-c66e-4484-92fe-e566c4ba8083.png)

**Comment by pubkey** [comment]
Hi @nothingkid 
So the reason is that in the past we only had pouchdb which creates the attachment digest by itself.
I think we should put that inside of RxDB instead so that the RxStorage implementation does not have to take care of it.
As I am preparing the next major release at the moment, you can create a PR if you want.
Otherwise I will put that into the backlog.

**Comment by pubkey** [comment]
I added the feature in 5d38ce475ffcd670b11e9a4f94d1f582e29a566f
