### ISSUE TITLE
ANNOUNCEMENT: Try out the beta of 11.0.0

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#3555]
Hello.
I am planning things for the next major version.
I have to make a new major release because I will add some breaking changes to make it possible to run the RxStorage inside of a WebWorker. So this is **your** chance to include other breaking changes.

- Breaking changes backlog: https://github.com/pubkey/rxdb/blob/master/orga/before-next-major.md
- Normal backlog: https://github.com/pubkey/rxdb/blob/master/orga/BACKLOG.md
- Current implemented changes for `11` https://github.com/pubkey/rxdb/blob/master/orga/releases/11.0.0.md

I am open for any other proposals, just write a comment about them here.

**Comment by beruic** [comment]
Please make sure there is a clear upgrad path, so you can upgrade without losing data.

**Comment by pubkey** [comment]
@beruic Yes I know :) There are no plans to change anything in the data layer. So the stored data does not have to be touched.

**Comment by 4321ip** [comment]
please, remove PouchDB deps when using LokiJS
#3545 https://github.com/pubkey/rxdb/issues/3545

**Comment by pubkey** [comment]
I released the beta of version `11`. Please try it out:
https://github.com/pubkey/rxdb/blob/master/orga/releases/11.0.0.md

**Comment by pubkey** [comment]
Released `11.0.0-beta.2`

**Comment by pubkey** [comment]
Released `11.0.0-beta.7`

**Comment by Hideman85** [comment]
That's sounds promising :rocket:, could it already been used to production? At the end what is the progress on it?

**Comment by pubkey** [comment]
@Hideman85 I am using the worker plugin in production with lokijs storage and incremental-indexeddb adapter.

Released `11.0.0-beta.10`

**Comment by Hideman85** [comment]
Looking very promising :slightly_smiling_face: 

I'm still wondering the pro/cons of `pouchdb-idb` vs `pouchdb-indexeddb`, have you even use the second one in real cases? It could be nice to add a comparison of them in your documentation.
I read that the second one is more efficient but do not fit yet 100% of couchdb but in a case of GQL sync it might be better.
I would appreciate your feedback on this.

**Comment by pubkey** [comment]
Released version `11.0.0` https://twitter.com/rxdbjs/status/1477993564265189378

**Comment by Hideman85** [comment]
Hi @pubkey thanks for the update.
May I request a sample for using `pouchdb-idb` worker instead of lockijs?
Basically following https://github.com/pubkey/rxdb/blob/master/docs-src/rx-storage-worker.md I can just swap the worker but what do I need to put in `statics`?

_Note: I'm using `pouchdb-idb` because my collection is not small enough to be placed in memory (specially if the client does have other activities opened)_

**Comment by pubkey** [comment]
I am not sure what is wrong. I have never tried out using pouchdb with the worker, [see](https://github.com/pubkey/rxdb/commit/d4ec11b79eabfb56fc374f24f1878ce747c23c88#diff-4d1469adaf99587ac0993100ac32ed99ec2b3fc0cd4ab078f8236ad94192b063R5)

**Comment by Hideman85** [comment]
I think it would be nice to support officially pouchdb since WebWorker is intended for bigger app and these could probably not fit in ram.
The file-loader import tell webpack to have a separate file and then workerInput is resolve as a url, I'm gonna console.log workerInput to be sure.

**Comment by pubkey** [comment]
Yes that would be nice. If you find out how to make it work, please update the docs so others can use it too.
I found several issues when I used the file-loader with angular for webworkers. So when you search for the error, it might be better to use the 'normal' method of loading the worker and then later you swap it out with the file-loader.

**Comment by Hideman85** [comment]
What do you mean by 'normal' method for loading the worker? workerInput need the url of the built worker file right?
If I don't tell anything to webpack then my file will be ignored, using file-loader tell webpack to add my file to dist and replace by a url.
I know this is working because I do the same for video.js library that I need worker too.

```js
import WebmWorkerUrl from 'file-loader!webm-wasm/dist/webm-worker.js' // eslint-disable-line
import WebmWasmUrl from 'file-loader!webm-wasm/dist/webm-wasm.wasm' // eslint-disable-line

options.plugins.record = {
              ...options.plugins.record,
              audio: false,
              convertEngine: undefined,
              videoEngine: 'webm-wasm',
              videoWorkerURL: WebmWorkerUrl,
              videoWebAssemblyURL: WebmWasmUrl,
              videoBitRate: 1200,
              videoFrameRate: 30
            }
```

**Comment by pubkey** [comment]
Ah sorry I confused sth here. Yes the file-loader will resolve into an url.
The `worker-loader` is the one that resolves to a blob.

**Comment by Hideman85** [comment]
I don't know that much the internal, maybe you can give me some hint.
What could cause the UT4 (adapter issue) to be thrown?
Does the worker scope need to to know something that he does not have access to?

From my experience with [worker-pouch](https://github.com/Hideman85/worker-pouch) the worker is built with the entire pouchdb and adapter but in that case this is because worker-pouch is a proxy adapter that pass down to a worker.
In case of the new implementation with internal RxDB worker I don't really now the requirements of the worker scope.

I'm gonna check thse source of your built-in pouch-worker I might find something.

**Comment by GHChrisSu** [comment]
Please add lokijs support for nodejs and cordova, you are soo great.

**Comment by GHChrisSu** [comment]
Currently I found lokijs adapters are only support for indexedDB, and nodejs do not have indexedDB, can you add nodejs and cordova adapter?  Thank you very much, you are soo great.

**Comment by Hideman85** [comment]
Hi @pubkey have you some update for the pouchdb indexedDB worker?
I'm currently having issues with my old quick fix and would like to switch to the official worker support.
Thank you in advance for your time :wink:

**Comment by Unforgiven-wanda** [comment]
@Hideman85 Can you please share a working repo for the fix you mentioned?

**Comment by Hideman85** [comment]
We are not using anymore RxDB in our project.
