### ISSUE TITLE
How do we secure the frontend?

### ISSUE THREAD

**Issue by malexdev** [pubkey/rxdb#36]
Hey there! Sorry if this is answered somewhere, I didn't see it when I looked around. 
As we all know, you can't trust the client. However, this library appears to allow the client to directly insert to its local database, that is then sync'd back to the server. 

Is there a way on the server to control what the client is allowed to do?
If so, does the client automatically recover from that (i.e. I change someone's username in my local database, then the server rejects so my app redraws with the corrected username from the server).

It's of course possible that I'm thinking about the use of this package all wrong. If so please let me know 😄

**Comment by pubkey** [comment]
Hi @malexdev .
Since RxDB relies on pouchdb, there are thousands of strategies available for your usecase.
When your client needs user-data from the server, you can do a readOnly-sync so that the client cannot change data. [See here](https://github.com/nolanlawson/pouchdb-authentication#couchdb-authentication-recipes).

**Comment by malexdev** [comment]
Ah, excellent. I was misunderstanding how this leverages Pouch. Thanks!
