### ISSUE TITLE
Is RxDB the better option? - RxDB as redux-store

### ISSUE THREAD

**Issue by zoomclub** [pubkey/rxdb#43]
I'm entirely new to RxDB but from the onset it does look like it may be a good fit, especially since I'm also a big fan of RxJS and Offline First solutions. 

While I work with the excellent VueJS framework I am finding the Vuex side limiting for my scenario. Vuex is essentially a store with modules and has a nice way of mapping state between Vue and Vuex. Firebase is the other service I'd like to work with but it also has it's limitations. For now I'll just list the things that are most important to me below, maybe RxDB is their solution?

• Offline First and the ability to run a local instance of RxDB, seems these are already included.

• A DB that has the essential CRUD functions onboard that can be applied to any store module. I have no interest in writing a bunch of actions, mutations and getters for Vuex modules. Just give me universal operations that take params so that they can perform on nodes in any collection without having to reinvent the basics.

• Full RxJS support where I can map/inject the observables to/from any nodes in my documents into Vue components. No GraphQL or special mapping, just simple RxJS IO please.

• Some way to sync to realtime services like Firebase. Not every document needs to be collaborated on, so all I require is to place a given document on Firebase during a session and then for RxDB changes to be synced to the realtime document. So all the changes would still only be made on the RxDB side and the sync would be automatic.

That's about it, hope the answers are just as simple as my requirements.

**Comment by pubkey** [comment]
1. Offline-First: Yes, RxDB relies on pouchdb which is designed to work completely offline-first. The online-sync with a server is optional.
2. CRUD-functions are included. But I dont geht what you mean with the actions,mutations, getters. Could you show an example of how the api should behave?
3. RxDB's observables are plain rxjs-observables/subjects. They emit either changeEvents or changed data.
4. There is currently no firebase-sync for RxDB/pouchDB. BUT you can sync with any couchDB-server or IBM cloudant.

**Comment by nickdandakis** [comment]
A database (RxDB) isn't a replacement for a state management library (Vuex). They provide different types of functionality. That's not to say you can't use this to replace Vuex, but you would be better off keeping your Vuex layer and integrating RxDB into your actions and mutators.

I see Firebase is also mentioned here, which at this point is a lot more than a realtime database or a storage solution. I'm going to assume that you're primarily using Firebase for realtime storage (rather than it's authentication for example). In which case, you'd be better off comparing this (after syncing to a remote CouchDB server like @pubkey said) to Firebase.

Great work btw @pubkey!

**Comment by zoomclub** [comment]
@pubkey "But I dont get what you mean with the actions,mutations, getters. Could you show an example of how the api should behave?". 

In my case I already have full models defined as JSON documents where the nodes of my documents are known (I can easily see applying the RxDB document schema). At this time I am starting to see that Vuex might be better for cases where there is data that is not well structured, so it is then a given to write action, mutation and getter functions for each small piece of the data as it arises during development.

Structure wise I'm inclined to see a RxDB database and a Vuex store as being on a similar level. Then to also see RxDB collections and Vuex stores at a similar level. Then with my structured documents being well defined I might just need generic functions to query, create, insert, update and remove nodes in the documents. Makes sense to me compared to writing a ton of broilerplate related Vuex functions for each specific piece of data there might happen to land in stores.

Here is what I want in the end. A database/store that has collections/store-modules to contain multiple versions of the different type of documents I already have. I then want to activate one of many possible documents stored in a given collection. The activated document per collection will be the target of edit operations made in components. Optionally, active documents can be synced through Firebase or some other realtime service for collaboration.

What I'm describing is likely very doable so I'm just wondering why I might need to wedge Vuex between RxDB and Vue components? With Vuex there is a side benefit of time-travel in developer mode only. That is not enough of a reason and I'd much rather implement a real undo/redo solution that is related to user editing instead.

The main thing then is, do the generic CRUD operations RxDB includes take parameters, so that they can target a given collection, document and node?

@nickdandakis I'm familiar with Vuex but it has no RxJS support or very robust Firebase support (vuex-fire only reads refs). Plus it seems like an extra layer of convention that I would rather not want to get bogged down with, especially since I already have structured data documents. 

When I look at the functionality of my app there is much more going on than just mutating end data nodes. This was my realization and why I'm looking to cut out middle man tasks if it is justified to do so. Given my description above and my specific document scenario why is it necessary to still use Vuex?

**Comment by pubkey** [comment]
Am I get this right that you want to use RxDB as replacement for a redux-like-store? Because if that is your intention, then RxDB is definately not the solution.

Disclaimer: I neither know vuejs nor vuex by more than 10%.

**Comment by zoomclub** [comment]
Hmm, it does not look like any of the RxDB examples work with a "redux-like-store" either. However, everyone in RxJS land knows the essence of Redux boils down to a one liner in RxJS 👍

**Comment by pubkey** [comment]
The problem I see is on the performance side. RxDB is a database and databases write things to disk. So when you have disk-io on every state-change, the performance will go to ground. 

You are right with the comparison from stores to rxdb. Indeed it would also be possible to time-travel because the underlaying pouchdb still contains the previous revisions after changes to the document. I will keep that in mind for future features.

I know redux but the first rule of redux is to [not use it if you dont need it](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367#.11859m431)  :smiley: .
So all cases I had, I prefered simple rxjs-observables instead of that big store that noone except the dude who said we need it, understood. But well, javascript is a dynamic language and we have dynamic opinions :smiley:

**Comment by zoomclub** [comment]
I'm actually just exploring the option of using RxDB as the database for all documents (instead of Firebase). The ability to share a given document and collaborate on it with a service like Firebase is a separate feature. Firebase is not complete anyways, no local cache, no document linking, poor query engine, etc.

Next I'm exploring if I will use Vuex or not. I really just want to load/activate specific documents from the RxDB backend and edit them using RxJS. When a activated document is saved it can be synced back to RxDB. 

I'm not yet sure what my local store should be, but something like the following is interesting: https://github.com/nramadas/Storable

Really like the following article: https://medium.com/@luijar/rxjs-pouchdb-persistent-data-flows-480f503ee41f#.fohpce56d

**Comment by pubkey** [comment]
@zoomclub I don't know how much free-time you have. But maybe, just maybe, you could create a vuejs-example for our [example-page](https://github.com/pubkey/rxdb/tree/master/examples) where you use RxDB together with vuejs in the way you are trying to archive with your exploration.
Of course I would help you where I can so we can find a solution where we both profit from.

**Comment by zoomclub** [comment]
@pubkey That sounds good and it's the goal I'm making progress toward. I'm presently reviewing related aspects and a clearer picture is emerging. In the way I'm tying the flow together there are two interesting discoveries: 

• The JSON documents I've defined are a form of 'virtual stores' and they can be exchanged so the app is configured with alternate behavior. So hardwiring Vuex stores is not the exciting thing here.

• The concept of state in Vuex stores goes to a new level. In the neo flow the state is just RxJS observables, which are connected to nodes in the local storage option. Of course other bits of data can exist in the store as state too.

I'm working through more details here but have a question related to what you mentioned earlier about "performance will go to ground". To be honest I'm not quite sure if RxDB uses Local Storage or IndexDB locally in the way I tend to think about it?

Likely RxDB uses an instance of Local Storage or alternate adapter for it's own purpose and it is indeed local? So if I query a RxDB collection and return an observable then is the state returned in the observable not ready for performant work? 

If so then do I need a separate instance of Local Storage? I'm thinking observables returned from queries and then becoming the state in a Vuex store would be as fast to work with as any other state? So its the returned observable that needs to be faster than the initial query!

**Comment by pubkey** [comment]
@zoomclub As storage engine, any pouchdb-adapter can be used. So you can use localstorage but also switch to indexeddb and many others if needed.
With my "performance goes to ground"-statement, please keep in mind that at this point I never thought about using RxDB as redux-store.

The problem lies on how RxDB is currently handling multi-instance-communication (multi-window in browsers or multi-process in nodejs). On older browsers, without the [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) and in nodeJS, RxDB creates an internal socket-like pouchdb where one RxDB writes on the left side and the other RxDB's read on the right side. The performance of this solution is acceptable when RxDB is used as "normal" database, but I see problems when you have many writes (I mean many many) like in the approach of using RxDB as store.

On newer browsers, all this is handled by the BroadcastChannel with a way better performance.

> So if I query a RxDB collection and return an observable then is the state returned in the observable not ready for performant work?
The observable from a RxQuery is ready for performant work. But keep in mind that the performance of an in-memory store will always be better than the performance of a disk-io-store.

**Comment by zoomclub** [comment]
Thanks for that clarification, make good progress today on the flow between RxJS and Vuex. I'm impressed with the API documentation and PouchDB. Also happy to meet many associated friends I have not seen around for a while, like json-schema, mquery and even metawidget!

**Comment by choma** [comment]
I'm trying to implement the same flow (RxDB + Vuex), but, since I'm a newbie, it's hard to me to realize how to put them together. It would be great if somebody could share some code (and maybe add it to /examples/vue?)

**Comment by motin** [comment]
> I'm trying to implement the same flow (RxDB + Vuex), but, since I'm a newbie, it's hard to me to realize how to put them together. It would be great if somebody could share some code (and maybe add it to /examples/vue?)

Yes, that would be great. Did you find some, @choma?
@zoomclub How did it go? Have any boilerplate / example / reusable code to share? I am in the same situation and would love to not have to reinvent the basics here. :)

**Comment by endlessuniverse** [comment]
> But I dont get what you mean with the actions,mutations, getters.

Example: https://www.npmjs.com/package/@platyplus/vue-rxdb-hasura
