### ISSUE TITLE
What did you pay for the hood.ie domain and would you be willing to hand it back to github.com/hoodiehq?

### ISSUE THREAD

**Issue by janl** [pubkey/rxdb#4433]
I had this domain lapse accidentally and had no luck getting it back from the inevitable domain grabber. Seems you were more lucky? :)

**Comment by pubkey** [comment]
Hi @janl 
I was not lucky enough to grab the domain :)
Instead some guy from bulgaria grabbed it ( this guy: https://seo.domains/ )
Since it was parked for so long, I wanted to buy it for the SEO-juice and the backlinks so I debated a price with him.
At the moment I still not "own" the domain, I signed a rent-to-lease via https://dan.com/ where I pay monthly (348€/month) to rent it and I will get ownership of the domain if I keep paying for the next 2 years.
The guy wanted 7500$ for a full buy.

I have no problem with giving the domain back to you. But you will have to to discuss a price with the current owner and then we can find out how I can transfer the rent-to-lease over to you.

By the way you can also write privately with me via discord if you want to.

**Comment by janl** [comment]
@pubkey thanks loads. 7.5k$ or 350€/mo is out of scope for the hoodie project. — if you end up keeping it, would you be up for adding a thing on the rx website if someone comes there via hood.ie that links to the project GitHub? Thanks loads and totally fine if you don’t have time for this!

**Comment by pubkey** [comment]
> if you end up keeping it, would you be up for adding a thing on the rx website if someone comes there via hood.ie that links to the project GitHub?

No sorry. This is also a big investment for me and either I get the full value with a 301 redirect, or I do not pay for the domain.

> ..is out of scope for the hoodie project.

Just ping me if that should change in the future.

**Comment by janl** [comment]
> No sorry. This is also a big investment for me and either I get the full value with a 301 redirect, or I do not pay for the domain.

I was imagining something super not intrusive, just a hop for folks that might get confused. but sure you do you
