### ISSUE TITLE
Conflict resolution not persisted

### ISSUE THREAD

**Issue by ofekd** [pubkey/rxdb#4608]
Using RxDB 14.6 with Loki, returning a conflict-resolved document from a custom conflict-handler does not persist, and instead the client-side version remains.

I am trying to debug this but am not sure where the code which persists the document is. I see that the collection is calling `resolveConflictResultionTask` in `rx-storage-helper.ts`, which is doing some transformations.

But then it returns `resolveConflictResultionTask` in `rx-storage-instance-loki.ts`, but that seems to return nothing. And even if it does return something meaningful, I cannot find where is it used.

Some pointers will be appreciated so I could debug more

Thanks

**Comment by pubkey** [comment]
`resolveConflictResultionTask` is used so that a storage can send a conflict "upwards". This is currently only used in the memory-synced storage.
In lokijs, the storage does never resolve a conflict, only RxDB does that and then calls the loki-storage bulkWrite() with the resolved document.
So to debug this, add logs to loki bulkWrite() and check if it gets called with the resolved conflict document.

**Comment by ofekd** [comment]
Thanks -- was able to debug `bulkWrite`, the problem was an `undefined` deletedFlag which resulted in the following error:

`Object { schemaPath: "#/required", keyword: "required", message: "must have required property '_deleted'", … }`

I see two possible issues here: (a) The error is not thrown, and (b) it shouldn't happen in the first place -- I have an alias field for `_deleted` and it is properly set in the backend. I am not sure where is it getting lost
