### ISSUE TITLE
Find docs with deep references?

### ISSUE THREAD

**Issue by simonwjackson** [pubkey/rxdb#475]
#### Psudeo Schemas 
```
platformsSchema
    ....

gamesSchema
    hasOne platform
    ...

launchersSchema
    hasMany platform
    ...
```
#### Psudeo Data
```
games = [{
    title: 'metroid',
    platform: 'nes'
}, {
    title: 'sonic',
    platform: 'genesis'
}]

platforms = [{
    id: 'nes'
}, {
    id: 'genesis'
}, {
    id: 'snes'
}]

launchers = [{
   title: 'nintendo emulator',
   platforms: ['nes', 'snes']
}]

```

#### Psudeo Query

```
filter out all games that do not have a launcher for their platform
```

#### Desired result

```
1 result: Metroid
```

After looking through the documentation, I cant seem to find a practical way to do this without manually looping through every result, populating each relationship waiting for all promises to resolve, and then filtering them via JavaScript. This seems like a expensive task to perform on the CPU.

Is there a native way to make a search like this in RxDB?

## Info
  - Environment: browser
  - Adapter: IndexedDB

**Comment by pubkey** [comment]
Hi @simonwjackson 
I think this problem is not RxDB but noSQL-specific.
The short answer is NO, you cannot do cross-collection-join on most nosql-databases.
You have to query one side and with the result you can query to other side and filter/modify the desired documents.

Doing this will of course need more CPU-cycles and more disk-IO then doing a simple query.
But let's compare this to a join-select on a mysql-database.
The mysql-server does not have a magic way to find all rows with a specified relation. In fact it will basically do the same like you do by hand in a nosql-database. It will run a select on one table and then aggregate this data to find all matches on the other table. This will probably take the same amount of CPU/IO than what you do at nosql by hand.

**Comment by simonwjackson** [comment]
Thanks for your feedback. I'm going to look into GraphQL and see if it fits for my project.

**Comment by errorx666** [comment]
I've written a couple of utility join functions.  I thought I'd share.

```ts
import { Observable, combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';

export const outerJoin = <T, U, K>( left: Observable<ReadonlyArray<T>>, right: Observable<ReadonlyArray<U>>, keyLeft: ( e: T ) => K, keyRight: ( e: U ) => K ) =>
	combineLatest( left, right ).pipe(
		map(
			( [ left, right ] ) => {
				if( !left ) return [];
				if( !right ) right = [];
				const idMap = new Map<K, U>();
				for( const r of right ) idMap.set( keyRight( r ), r );
				return left.map( l => ( [ l, idMap.get( keyLeft( l ) ) ] as [ T, U|undefined ] ) );
			}
		)
	);

export const innerJoin = <T, U, K>( left: Observable<ReadonlyArray<T>>, right: Observable<ReadonlyArray<U>>, keyLeft: ( e: T ) => K, keyRight: ( e: U ) => K ) =>
	outerJoin<T, U, K>( left, right, keyLeft, keyRight )
	.pipe(
		map( lr => lr.filter( ( [ , r ] ) => r != null ) )
	);
```

Usage:
```ts
innerJoin(
   from( games ),
   from( platforms ),
   game => game.platform,
   platform => platform.id
)
.subscribe( gamePlatforms => {
    for( const [ game, platform ] of gamePlatforms ) {
        console.log( game, platform );
    }
} );

**Comment by Unforgiven-wanda** [comment]
How would this answer work if you're trying to join over a value and an array, or the intersection of two arrays?
