### ISSUE TITLE
nats example

### ISSUE THREAD

**Issue by gedw99** [pubkey/rxdb#4774]
hey 

nats is alpha / beta but good to make an example.

we can also add README for setting up NATS jetstream and also securing it with nsc.

https://github.com/nats-io/nsc

https://nats-io.github.io/nsc/

then connect using context on nats cli.

---

then work out how to map jwts ( from any authority )  to nats jwt

---

then on server validate data using json schema, etc 
then run the example

**Comment by pubkey** [comment]
Related: https://github.com/ConnectEverything/nats-by-example/issues/112

**Comment by pubkey** [comment]
Hey. So I looked more into this and I think at this point in time, NATS is just not a good solution for server-client replication, because there is not validation etc on the nats side. Maybe https://github.com/ConnectEverything/nats-by-example/issues/112 will clear up some things.

I am closing this because in the near future I am not planning to add any more NATS stuff by myself, PR is welcomed.

**Comment by gedw99** [comment]
Hey @pubkey 

Feeding the reactive db from nats would be easy. Nats on server I mean.

don’t know if that’s useful though ?
