### ISSUE TITLE
react native : Can't find variable: BigInt

### ISSUE THREAD

**Issue by jwallet** [pubkey/rxdb#5386]
using the 15.0.0-beta.42 (cannot use .43 since it was not published for premium)

On react native ESMA Script 2020 seems to not be shipped with it, so we get an issue with BigInt https://github.com/facebook/react-native/issues/28492

the solution suggested is to add a new dependency but does not work, for both libs suggested, maybe adding it to babel plugins will work

[image](https://github.com/pubkey/rxdb/assets/23088305/a4ad4eeb-1440-41a3-82c8-f15974582de5)

**Comment by pubkey** [comment]
I think this is coming from the mingo library here https://github.com/kofrasa/mingo/blob/585992064ee2830eb78437ef15907c67b817bc53/src/util.ts#L90

**Comment by pubkey** [comment]
I created an issue https://github.com/kofrasa/mingo/pull/407

**Comment by jwallet** [comment]
After using patch-package it loaded and synchronized properly on v15. However patching lib was only used to go a bitter further and see if v15 breaks a expo project, but no it's just like v14.

- React native with expo, node 20, TS 5
- Sqlite storage with expo-sqlite-storage
- Graphql replication
- with you since v12

The newest expo sdk is coming with a new expo-sqlite version. I wonder if they updated it to the newest Android API which I think supports json_extract or maybe Im mistaking with xandroid

**Comment by pubkey** [comment]
This [issue about sqlite android version in expo](https://expo.canny.io/feature-requests/p/expo-sqlite-ship-newer-sqlite3-version-on-android) is still open and has no new comments, so I am not sure. [Here](https://news.ycombinator.com/item?id=36882064) @ide said they work on the sqlite update, but this was some months ago.

**Comment by jwallet** [comment]
there are mentions to sqlite3 with the latest [sdk50](https://github.com/expo/expo/blob/sdk-50/packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt), if you go back to the branch [sdk49](https://github.com/expo/expo/blob/sdk-49/packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt) you will see the current code

**Comment by ide** [comment]
The [next](https://docs.expo.dev/versions/unversioned/sdk/sqlite-next/) version of expo-sqlite will include SQLite as a dependency allowing for SQLite extensions like CR-SQLite and for the library to be kept more up to date than the OS vendors do.

There is also an entirely new API exported from expo-sqlite/next that provides both sync and async functions (sometimes sync functions simplify your code so much it’s worth blocking the JS thread), Uint8Array support (storing blobs), prepared statements (when running one query many many times), a more native JS API with iterators and async iterators, and a more native React API with Context and Suspense. There is also support for Hermes BigInts, which has come up in API design discussions.

Since it is a new API, new adapters will need to be written. However, our hope is that it’s a mostly straightforward, mechanical change. 

You can try the beta version of the package today. We are still discussing a couple more edge cases of the API before the non-beta release so there may be small breaking changes to the API during the beta period (things like varargs vs. explicit arrays). However, I expect the changes to be easy to keep up to date with if you decide to explore using the beta. [SDK 50 beta notes](https://expo.dev/changelog/2023/12-12-sdk-50-beta)

**Comment by pubkey** [comment]
@ide  Thank you so much for the detailed answer of our question. Looking forward to SDK50.

@jwallet I am closing this issue because the original problem has been fixed and the mingo release has been added to RxDB.
