### ISSUE TITLE
Wrong document data when live syncing

### ISSUE THREAD

**Issue by gvuyk** [pubkey/rxdb#543]
## Case
Bug

## Issue
Tried to live-sync several collections with a remote couchdb. After restarting the app, I started to get data from collection A when querying collection B

## Info
  - Environment: Node.js / electron
  - Adapter: LevelDB / memory

## Code

[Test case](https://github.com/pubkey/rxdb/pull/544)

**Comment by pubkey** [comment]
Hi @gvuyk 
Thank you for the PR, I could now figure out what the problem is.
`await SpawnServer.spawn();` returns a path to a single collection-endpoint, not to the couchdb-info-path.
This means, to sync two collections, you should use two different endpoints, not the the same one for both collections.
For example calling `spawn()` once, returns `http://localhost:12127/db/3ciqr/` where `http://localhost:12127/db/` is the couchdb-endpoint, but `3ciqr` points to a single collection.

**Comment by gvuyk** [comment]
I see now, I was expecting couchdb to support collections just like mongodb. Thanks for taking the time :)

So, to live-sync multiple collections (17+), I'll create a new instance of PouchDB for each of them and use these instances as their `remote` in their `sync` method
Each instance will point to a remote couchdb database
Is this the correct way?

**Comment by pubkey** [comment]
Yes
