### ISSUE TITLE
Syncing 3rd party with collection data

### ISSUE THREAD

**Issue by marbemac** [pubkey/rxdb#5481]
Another question - lmk if you'd prefer these questions somewhere else other than GH issues!

I was digging into the Flexsearch plugin, which uses rxdb insert/save/remove hooks to attempt to keep the local flexsearch index in sync with the target rxdb collection (https://github.com/serenysoft/rxdb-flexsearch/blob/master/src/index.ts#L85-L107).

However, none of these hooks are invoked in response to remote changes (e.g. via replication w external server). So for example: 

- if user logs out (and we delete the local db on logout), and then logs back in, the local rxdb db will be built back up via sync but I don't see a way to keep something like flexsearch in sync (other than more custom logic inside the custom replication handler itself).
- on re-sync, the pull handler returns a document that was updated or added since last sync, rxdb updates that doc in the local db to reflect the change, but there doesn't seem to be a way to hook into this behavior

Might it make sense to introduce a new hook(s), or add an option to existing hooks, to cover the use case where one needs to observe/react to the state of the local db? Or perhaps this is possible by using lower level subscription to the collection or something that I just haven't noticed - the hooks system just caught my eye as the most likely to cover this need.

**Comment by pubkey** [comment]
> none of these hooks are invoked in response to remote changes

This is correct and intentional. The hooks run outside of the RxStorage in the "RxDB Layer" so when the inner storage is called by some plugin, the hooks will not be triggered.

> Or perhaps this is possible by using lower level subscription to the collection

This. Keeping another storage in sync by just listening to the hooks is dangerous. The browser might crash in between a write and the new write that happens dependend on it.
Instead it should iterate the checkpoints like other plugins do it.
For your use, have a look at the backup plugins code, this might be the better option for flexsearch: https://github.com/pubkey/rxdb/blob/master/src/plugins/backup/index.ts#L123

**Comment by leandrogehlen** [comment]
Hello @marbemac, i'm the maintainer of rxdb-flexsearch.
I didn't have time to implement this feature. Feel free to implement the pull request (PR).
