### ISSUE TITLE
Update the RxDB Examples so that they use the new RxServer for replication instead of the pouchdb/couchdb server.

### ISSUE THREAD

**Issue by mattriese** [pubkey/rxdb#5584]
I'm working on the "Premium Task" of upgrading the examples to use RxServer for replication instead of pouchdb/couchdb. 

I plan to have it done by Feb 11th

**Comment by pubkey** [comment]
@mattriese Awesome! If you have any trouble just write here so I will try to help.

**Comment by pubkey** [comment]
Hi @mattriese , if you are already working on this please stop. There is a problem I haven't thought about:
When we add the rxdb-server plugin as a dependency to the rxdb repo, we can no longer introduce any breaking changes while still making the CI green because it would then run the e2e tests of the examples on an non-compatible version of rxdb-premium.

**Comment by mattriese** [comment]
Ok sure I'll stop and tey to think on it.

**Comment by pubkey** [comment]
Closing this, I removed the task from the list.
