### ISSUE TITLE
Array.push is not proxied

### ISSUE THREAD

**Issue by DerekTBrown** [pubkey/rxdb#561]
## Case
Bug

## Issue
Assume we have a document with a property `arr` that is an array.  We would expect `document.arr.push(3)` to append to the document. However, this push is not persisted.

## Info
  - Environment: Chrome/Firefox
  - Adapter: IndexedDB
  - Stack: Typescript + Angular

## Code

```js
  var document = collection.newDocument({
      arr: []
  });

  document.arr.push(3); // returns 1 - indicating push worked.

  console.log(document); // returns []

```

**Comment by pubkey** [comment]
Hi @DerekTBrown 
I'm sorry but it's currently not possible to directly mutate arrays in the proxy-getter/setter.
The reason is that to have IE11-Support, we could not use the [Proxy-Object](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Proxy).
I now added [a notice](https://github.com/pubkey/rxdb/blob/master/docs-src/rx-document.md#proxy-set) to the docs, so other users do not have the same problem.
In the future we might drop IE11-Support and allow direct mutations, [described here](https://github.com/pubkey/rxdb/blob/master/orga/before-next-major.md#use-proxy-instead-of-getterssetter-on-rxdocument)
