### ISSUE TITLE
Omitting JSON Schema on RxDatabase#collection creates runtime exception

### ISSUE THREAD

**Issue by RickCarlino** [pubkey/rxdb#58]
I recently ran `dbInstance.collection("my_collection")` and got the following error:

```
main.bundle.js:37243 Uncaught (in promise) TypeError: Cannot read property 'hash' of undefined
    at RxDatabase._callee5$ (http://localhost:3002/js/main.bundle.js:37243:53)
    at tryCatch (http://localhost:3002/js/main.bundle.js:28199:41)
```
[Link to source code raising exception](https://github.com/pubkey/rxdb/blob/d884766d2e89b3be7440d109dbed6e27a54b0bf5/dist/lib/RxDatabase.js#L435)

I was able to fix the issue by calling `dbInstance.collection("my_collection", MY_JSON_SCHEMA)`.

Possible Solutions:

 1. Mark field as required in Typescript typing
 2. Perform a nil check at runtime describing the issue.

Wanted to post this up here incase anyone is googling the same errorr.

@pubkey Are my assumptions here correct? I can get a fix in the coming days if so.

**Comment by pubkey** [comment]
Hi @RickCarlino 
The schema on `collection()` is required at the first run, because this will create the collection.
At the second use of `collection()`, you only need the collection-name because it will return the existing one.

I know this is not the best solution, this is why I changed it in the comming version 3, see [here](https://github.com/pubkey/rxdb/blob/3.0.0/docs/RxCollection.md#get-a-collection-from-the-database).

**Comment by RickCarlino** [comment]
Ah great, I will start using 3.0.0 then.
