### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': #<Object> could not be cloned.

### ISSUE THREAD

**Issue by radiantone** [pubkey/rxdb#5990]
Happens when I call `document.remove()`

OS: Pop!_OS_22.04 (Ubuntu)
GOogle Chrome

![image](https://github.com/pubkey/rxdb/assets/25509097/08aa5cdd-6eeb-4000-8703-f525983721aa)

**Comment by pubkey** [comment]
https://github.com/pubkey/rxdb/issues/5046

**Comment by francois-codes** [comment]
We're seeing that issue as well but in our case, saving arrays in rxdb works, however we're getting that error when multi instance is enabled and the lib tries to send `eventBulk` via broadcast channel

wrapping the `eventBulk` object in a function that removes prototypes fixes the issue. 

I read your previous comment @pubkey that you didn't want to serialize / deserialize but in this case I don't think it's in the critical path (BC call is made after writes are processed to notify other tabs if I understand correctly).

Happy to push a PR if that can be helpful suppressing this error for people using multi instance with plain JS objects and still seeing this data clone error

**Comment by pubkey** [comment]
@francois-codes 
It would still use the CPU heavily after each write.
What type of object do you pass that causes the error? Can you make a PR with a test case?

**Comment by francois-codes** [comment]
sure, but not in the critical path, so while it might slightly increase resource consumption, it shouldn't slow down the lib
My understanding is that this is used to propagate changes that are performed in one tab to another.

I'll try to send you a repro. 
I don't think the type of data saved matters. The error happens here https://github.com/pubkey/rxdb/blob/00d50df6749eb33c3f075070e42cf32d9955dd0a/src/rx-storage-multiinstance.ts#L146
and is caused by `eventBulk` having an array with a prototype. this object is constructed internally by rxdb, so the payload saved to rxdb doesn't really matter from what I saw.

I've patched it roughly with this:

```tsx
function deepCloneNoProto(obj) {
  if (obj === null || typeof obj !== "object") return obj;
  if (Array.isArray(obj)) return obj.map(deepCloneNoProto);
  const clone = Object.create(null);
  for (const key of Object.keys(obj)) {
    clone[key] = deepCloneNoProto(obj[key]);
  }
  return clone;
}

// ...
const clonedEventBulk = deepCloneNoProto(eventBulk)

     broadcastChannel.postMessage({
       storageName: storageName,
       databaseName: instanceCreationParams.databaseName,
       collectionName: instanceCreationParams.collectionName,
       version: instanceCreationParams.schema.version,
       eventBulk
       eventBulk: clonedEventBulk
     });

```
it's been running on our staging env for 24 hours and we haven't noticed anything unexpected so far

**Comment by pubkey** [comment]
I see. Can you make a failing test case to reproduce the error?
