### ISSUE TITLE
reduce the bundle size.

### ISSUE THREAD

**Issue by xialvjun** [pubkey/rxdb#61]
The size of `rxdb.browserify.min.js` is `521KB` at commit [e0b3580](https://github.com/pubkey/rxdb/commit/e0b358045fba48a4da62268f64df79205d19cceb)......

Hope it be thinner.

**Comment by pubkey** [comment]
I did some tests with rollup where the size could be reduced by 30%. Also in v3 the polyfills will not be added and rxjs will be a peer dependency. The gziped code should be under 100KB in the near future. Also playing arround with other dependencies should have a huge impact since crypto.js and jsonschema is currently to big.

**Comment by pubkey** [comment]
btw you can run `npm run disc` to see which dependencies takes how much space.

**Comment by pubkey** [comment]
I'm closing this for now.
We have to w8 until pouchdb releases the next version so that we can do proper tree-shaking on the imports.
From there I will start optimizing the build-size.

**Comment by itbrandonsilva** [comment]
Any updates in this area?

**Comment by pubkey** [comment]
Hi @itbrandonsilva 
The full build-size (rxdb+dependencies, minified+gziped) has now 161kb, you can verify this by running `npm run build:size`
We also now have the option to do a [custom-build](https://pubkey.github.io/rxdb/custom-build.html) which will further decrease the size
