### ISSUE TITLE
"completed" not fired on observable

### ISSUE THREAD

**Issue by hirokiosame** [pubkey/rxdb#732]
## Case
Bug

## Issue
"completed" is not emitted when subscribing to a rxquery observable.

## Code
```js
db.user.findOne({ username: { $eq: username } }).$
	.subscribe({
		next: entry => console.log({ entry }),
		complete: () => console.log('completed'),
```

**Comment by hirokiosame** [comment]
The lack of `completed` not firing is also preventing [`Observable#.toPromise()`](https://github.com/ReactiveX/rxjs/blob/3b290ea76e76ef66f9d0c641d4db0da53a9cbaea/spec/operators/toPromise-spec.ts#L7) from working (which I think should yield the same result as `#exec()`).

**Comment by pubkey** [comment]
The question is when should an observable be completed?
Observing a database-query is never completed because there could always be a change to the database which will emit a new result-array.

If you want to use `toPromise`, you could do `myQuery.pipe(first()).toPromise()`, this would then do the same as `exec()`.

**Comment by hirokiosame** [comment]
I see. Perhaps `findOne()` should "complete" after one result then. I can open a PR for that if you'd like.

Is there a way to retrieve all the rows of a database that match a query _just at the time of execution_?

**Comment by pubkey** [comment]
No, `findOne` also emits values until the db is closed.
