### ISSUE TITLE
inMemory collections don't sync up removals

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#754]
## Case
Bug; inMemory collections don't sync up the removal of documents.

## Issue
When a doc is removed on an inMemory, it is still present in its original collection, and also vice versa.

## Info
  - Environment: Browser
  - Adapter: idb, memory
  - RxDB: 7.7.1

## Code

```js
const RxDB = require('rxdb');
RxDB.plugin(require('pouchdb-adapter-idb'));
RxDB.plugin(require('pouchdb-adapter-memory'));

async function test() {
  const db = await RxDB.create({
    name: 'testdb',
    adapter: 'idb',
    multiInstance: false
  });

  const schema = {
    version: 0,
    type: 'object',
    primaryPath: '_id',
    properties: {
      name: {
        type: 'string'
      }
    }
  };

  const collection = await db.collection({
    name: 'person',
    schema: schema,
    statics: {
      one() {
        return this.findOne();
      }
    }
  });

  // Insertion
  console.log('-'.repeat(20));
  const inMemCollection = await db.collections.person.inMemory();
  collection.insert({ name: 'hi' });
  // Wait
  await new Promise((resolve) => setTimeout(resolve, 1000));
  const inserted = await inMemCollection.findOne().exec();
  console.log(
    'Name in sync with inMemory?',
    inserted && inserted.name === 'hi'
  );

  // Removal from collection
  console.log('-'.repeat(20));
  console.log('Removing from collection');
  await collection
    .findOne()
    .exec()
    .then((x) => x.remove());
  // Wait
  await new Promise((resolve) => setTimeout(resolve, 2000));
  console.log(
    'Was removed from collection?',
    (await collection.findOne().exec()) === null
  );
  console.log(
    'Was removed from inMemory collection?',
    (await inMemCollection.findOne().exec()) === null
  );
  console.log('-'.repeat(20));
}
test();
```

**Comment by rafamel** [comment]
This might be related to #761

**Comment by pubkey** [comment]
Ok this was a hard one :)

First problem was that as described in #761 `.remove()` did delete all data of the document. I always thought remove would do the same as only setting `_deleted: true` which was wrong, I changed it and we now use `pouch.put()` and only set the _deleted-flag

Also there was a bug in the query-change-detection which is fixed now.

Because `pouch.bulkDocs` does not work for deleting documents silently, I added a workaround which could be removed in the future when the added pouch-db-integration-test fails.

**Comment by rafamel** [comment]
Amazing work, Daniel!

**Comment by hubgit** [comment]
@pubkey If a document is deleted remotely and syncs to the local database with the data deleted (as with the old behaviour of `.remove()`), will the query change detector still handle it correctly?

In other words, if a deleted document used to match the query and now doesn't match the query (because it doesn't have any of the matching properties), will the query subscriber still be called?
